// src/server/stateMachine.ts — Game state transition logic for all game types

import type {
  BingoGame,
  BingoGameState,
  Game,
  GameState,
  TriviaGame,
  TriviaGameState,
} from "@/shared/types";
import { isValidBingoTransition, isValidTriviaTransition } from "@/shared/gameStates";

export interface TransitionResult {
  success: boolean;
  from: GameState;
  to: GameState;
  error?: string;
}

/**
 * Check if a transition from one state to another is valid for the given game's type.
 */
export function canTransition(game: Game, to: GameState): boolean {
  if (game.type === "trivia") {
    return isValidTriviaTransition(game.state, to as TriviaGameState);
  }
  return isValidBingoTransition(game.state, to as BingoGameState);
}

/**
 * Attempt a state transition. Returns success/failure with context.
 */
export function validateTransition(game: Game, to: GameState): TransitionResult {
  if (!canTransition(game, to)) {
    return {
      success: false,
      from: game.state,
      to,
      error: `Invalid transition from ${game.state} to ${to}`,
    };
  }

  return {
    success: true,
    from: game.state,
    to,
  };
}

/**
 * Apply a state transition to a trivia game, including side effects.
 */
function triviaTransition(game: TriviaGame, to: TriviaGameState): TriviaGame {
  const updatedGame: TriviaGame = { ...game, state: to };

  switch (to) {
    case "ROUND_INTRO": {
      // When entering ROUND_INTRO, mark the current round as active
      const rounds = updatedGame.rounds.map((round, i) => {
        if (i === updatedGame.currentRoundIndex) {
          return { ...round, state: "active" as const };
        }
        return round;
      });
      updatedGame.rounds = rounds;
      break;
    }

    case "QUESTION_DISPLAY": {
      // When entering QUESTION_DISPLAY, clear timer info
      // (the actual timer starts on ANSWERING)
      updatedGame.timerStartedAt = null;
      updatedGame.timerDuration = null;
      break;
    }

    case "ANSWERING": {
      // Start timer for the current question
      const round = updatedGame.rounds[updatedGame.currentRoundIndex];
      const question = round?.questions[updatedGame.currentQuestionIndex];
      if (question) {
        updatedGame.timerStartedAt = Date.now();
        updatedGame.timerDuration = question.timeLimit;
      }
      break;
    }

    case "REVIEWING": {
      // Stop the timer
      updatedGame.timerStartedAt = null;
      updatedGame.timerDuration = null;
      break;
    }

    case "SCORE_REVEAL": {
      // Scores have been calculated — no additional side effects needed
      break;
    }

    case "ROUND_RESULTS": {
      // Mark the current round as completed
      const rounds = updatedGame.rounds.map((round, i) => {
        if (i === updatedGame.currentRoundIndex) {
          return { ...round, state: "completed" as const };
        }
        return round;
      });
      updatedGame.rounds = rounds;
      break;
    }

    case "GAME_OVER": {
      // No special side effects — final rankings are computed by the caller
      break;
    }

    case "LOBBY": {
      // Reset for a new game (GAME_OVER → LOBBY)
      // Clear answers, reset scores, keep players
      const players = { ...updatedGame.players };
      for (const playerId of Object.keys(players)) {
        players[playerId] = {
          ...players[playerId],
          score: 0,
          answers: {},
        };
      }
      updatedGame.players = players;
      updatedGame.currentRoundIndex = 0;
      updatedGame.currentQuestionIndex = 0;
      updatedGame.timerStartedAt = null;
      updatedGame.timerDuration = null;

      // Reset all rounds to pending
      updatedGame.rounds = updatedGame.rounds.map((round) => ({
        ...round,
        state: "pending" as const,
      }));
      break;
    }
  }

  return updatedGame;
}

/**
 * Apply a state transition to a bingo game, including side effects.
 */
function bingoTransition(game: BingoGame, to: BingoGameState): BingoGame {
  const updatedGame: BingoGame = { ...game, state: to };

  switch (to) {
    case "BINGO_PLAYING": {
      // Cards are generated by handleStartBingoGame before this transition runs
      break;
    }

    case "BINGO_ENDED": {
      // No special side effects — winners list is already authoritative
      break;
    }

    case "LOBBY": {
      // Reset for a new game (BINGO_ENDED → LOBBY): clear cards/winners, reset scores
      const players = { ...updatedGame.players };
      for (const playerId of Object.keys(players)) {
        players[playerId] = { ...players[playerId], score: 0 };
      }
      updatedGame.players = players;
      updatedGame.cards = {};
      updatedGame.winners = [];
      break;
    }
  }

  return updatedGame;
}

/**
 * Apply a state transition to the game, dispatching to the type-specific
 * transition function. Returns a new Game object with updated state.
 */
export function transition(game: Game, to: GameState): Game {
  if (game.type === "trivia") {
    return triviaTransition(game, to as TriviaGameState);
  }
  return bingoTransition(game, to as BingoGameState);
}

/**
 * Determine the next state based on the current trivia state and game context.
 * Used for SCORE_REVEAL → next and ROUND_RESULTS → next decisions.
 */
export function getNextState(
  currentState: TriviaGameState,
  context: {
    hasMoreQuestions: boolean;
    hasMoreRounds: boolean;
  },
): TriviaGameState | null {
  switch (currentState) {
    case "SCORE_REVEAL":
      return context.hasMoreQuestions ? "QUESTION_DISPLAY" : "ROUND_RESULTS";
    case "ROUND_RESULTS":
      return context.hasMoreRounds ? "ROUND_INTRO" : "GAME_OVER";
    default:
      return null;
  }
}
